# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestFirebaseRN' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TestFirebaseRN
  pod 'Firebase/Core'

  target 'TestFirebaseRN-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TestFirebaseRNTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
